use std::collections::HashSet;

use crate::scanner::Discovered;
use crate::classifier;
use crate::types::{NavEntry, CtxEntry, CompilerConfig};

/// Curate discovered resources into @NAV entries.
/// This is where we decide what's worth including in the manifest.
pub fn curate(
    discovered: &[Discovered],
    config: &CompilerConfig,
    session_enrichments: &std::collections::HashMap<String, String>,
) -> (Vec<NavEntry>, Vec<CtxEntry>) {
    let mut nav = Vec::new();
    let mut used_ids: HashSet<String> = HashSet::new();

    for (i, d) in discovered.iter().enumerate() {
        let (resource_type, mut about) = classifier::classify(d);

        // Enrich description from session logs if available
        let path_str = d.path.to_string_lossy().to_string();
        if let Some(enrichment) = session_enrichments.get(&path_str) {
            if enrichment.len() > about.len() {
                about = enrichment.clone();
                if about.len() > config.max_about_len {
                    about = format!("{}...", &about[..config.max_about_len - 3]);
                }
            }
        }

        // Generate unique ID
        let mut id = classifier::generate_id(&d.path, &d.kind, i);
        let base_id = id.clone();
        let mut suffix = 2;
        while used_ids.contains(&id) {
            id = format!("{}{}", base_id, suffix);
            suffix += 1;
        }
        used_ids.insert(id.clone());

        // Calculate token cost
        let tokens = estimate_tokens(d.size_bytes);

        // Default load hints
        let load_hints = classifier::default_load_hints(&d.kind);

        // Add trailing slash for directories
        let path = if d.is_dir && !d.path.to_string_lossy().ends_with('/') {
            d.path.join("")
        } else {
            d.path.clone()
        };

        nav.push(NavEntry {
            id,
            resource_type,
            path,
            about,
            tokens,
            load_hints,
        });
    }

    // Generate default @CTX
    let ctx = generate_default_ctx(config, &nav);

    (nav, ctx)
}

/// Estimate token count from byte size.
/// Uses chars/4 heuristic — same as the FOUNDATION session monitor.
fn estimate_tokens(bytes: u64) -> usize {
    (bytes as f64 / 4.0).ceil() as usize
}

/// Generate a default @CTX section from project metadata.
fn generate_default_ctx(config: &CompilerConfig, nav: &[NavEntry]) -> Vec<CtxEntry> {
    let mut ctx = Vec::new();

    // Status
    let mermaid_count = nav.iter().filter(|n| n.resource_type == crate::types::ResourceType::MRM).count();
    let dec_count = nav.iter().filter(|n| n.resource_type == crate::types::ResourceType::DEC).count();
    let dir_count = nav.iter().filter(|n| n.resource_type == crate::types::ResourceType::DIR).count();

    ctx.push(CtxEntry {
        key: "status".into(),
        value: format!(
            "Project indexed: {} resources ({} diagrams, {} decisions, {} source dirs).",
            nav.len(), mermaid_count, dec_count, dir_count,
        ),
    });

    // Timestamp
    let now = chrono::Utc::now().format("%Y-%m-%d");
    ctx.push(CtxEntry {
        key: "compiled".into(),
        value: format!("{} — auto-generated by aimf compiler.", now),
    });

    // Total token budget
    let total_tokens: usize = nav.iter().map(|n| n.tokens).sum();
    let design_tokens: usize = nav.iter()
        .filter(|n| n.load_hints.iter().any(|h| h == "design"))
        .map(|n| n.tokens)
        .sum();
    ctx.push(CtxEntry {
        key: "token_budget".into(),
        value: format!(
            "Full load: ~{} tokens. Design mode: ~{} tokens.",
            total_tokens, design_tokens,
        ),
    });

    if let Some(ref repo) = config.repo {
        ctx.push(CtxEntry {
            key: "repo".into(),
            value: repo.clone(),
        });
    }

    // Prompt user to fill in the rest
    ctx.push(CtxEntry {
        key: "focus".into(),
        value: "[edit this: what area is active right now]".into(),
    });
    ctx.push(CtxEntry {
        key: "next".into(),
        value: "[edit this: what should happen next]".into(),
    });

    ctx
}
